# NOTE: move this answer file up a directory for it to work

# Assignment Requirements
# db must only run on a node with ssd=true label
# vote should be HA with 2 replicas
# vote must not run on Swarm manager nodes
# worker needs to scale with Swarm worker nodes, 1 task each

version: '3.9'
services:
    viz:
      image: bretfisher/visualizer
      volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
      ports:
          - "8080:8080"
      deploy:
          placement:
              constraints:
                  - node.role == manager
    redis:
        image: redis:alpine
        networks:
            - frontend
    db:
        image: postgres
        volumes:
            - 'db-data:/var/lib/postgresql/data'
        networks:
            - backend
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        deploy:
            placement:
                constraints:
                    - node.labels.ssd == true
#                    - node.role == manager
    vote:
        image: bretfisher/examplevotingapp_vote
        ports:
            - '5000:80'
        networks:
            - frontend
        deploy:
            replicas: 2
            placement:
                constraints:
                    - node.role == worker
    result:
        image: bretfisher/examplevotingapp_result
        ports:
            - '5001:80'
        networks:
            - backend
    worker:
        image: bretfisher/examplevotingapp_worker
        networks:
            - frontend
            - backend
networks:
    frontend: null
    backend: null
volumes:
    db-data: null
